name: readthedocs
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - ca-certificates=2022.3.18
  - certifi=2021.10.8
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libstdcxx-ng=9.3.0
  - ncurses=6.3
  - openssl=1.1.1n
  - pip=21.2.2
  - python=3.7.9
  - readline=8.1.2
  - sqlite=3.38.0
  - tk=8.6.11
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - alabaster==0.7.12
    - babel==2.9.1
    - charset-normalizer==2.0.12
    - commonmark==0.8.1
    - docutils==0.17.1
    - future==0.18.2
    - idna==3.3
    - imagesize==1.3.0
    - importlib-metadata==4.11.3
    - jinja2==3.1.0
    - markupsafe==2.1.1
    - mock==1.0.1
    - packaging==21.3
    - pillow==5.4.1
    - pygments==2.11.2
    - pyparsing==3.0.7
    - pytz==2022.1
    - readthedocs-sphinx-ext==2.1.5
    - recommonmark==0.5.0
    - requests==2.27.1
    - setuptools==58.2.0
    - snowballstemmer==2.2.0
    - sphinx==4.4.0
    - sphinx-rtd-theme==1.0.0
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - typing-extensions==4.1.1
    - urllib3==1.26.9
    - zipp==3.7.0
